### ISSUE TITLE
APiManagerStub or Sample Data Can not found Error 

### ISSUE THREAD

**Issue by Do-hyun-Kim** [Connect-SideProject/connect-iOS#15]
시원님 저번에 Assetes 하고 Then 추가하신 Branch를 develop에서 Pull 받아서 했는데  Sample Data 부분에서 Error 가 나서 아마 Profile쪽 작업하신 부분이 없어서 그런것 같은데 확인 부탁 드릴 게용~!! 
<img width="1223" alt="스크린샷 2022-08-18 오후 9 43 33" src="https://user-images.githubusercontent.com/23008224/185397593-0c9011df-fdf6-454c-86ee-439c9d7f5388.png">

**Comment by butter-free** [comment]
develop 반영하여 close 합니다
