### ISSUE TITLE
MainController issue

### ISSUE THREAD

**Issue by Do-hyun-Kim** [Connect-SideProject/connect-iOS#4]
#2 MainController에 NavigationController가 없다보니 HomeViewController에 SearchBar를 생성 할수 없습니다.

- [x]  TabbarController만 존재, NavigationBar nil 값
- [x] TabbarController -> NavigationController -> ViewController로 수정해야 할것 같습니다. ^^

**Comment by butter-free** [comment]
@Do-hyun-Kim 

HomeViewController 생성 코드에서 NavigationController를 생성하고 
rootViewController를 HomeViewController로 지정하는 방식은 어떠신가요?

MainController(탭바)에 포함되는 화면(홈, 지도, 채팅, My)이 모두 Navigation 처리를 할것인지
아직 명확한 기획이 정해진게 아니라서 한번 검토 부탁드리겠습니당

**Comment by Do-hyun-Kim** [comment]
@butter-free  아하 그럼 그부분은 확인 후에 작업 진행하겠습니다 ^^

**Comment by dlrjswns** [comment]
엇 저 이 부분 전에 그냥 custom으로 searchBar를 넣어주었는데 UINavigationController로 MapViewController덮고 searchBar를 titleView로 다시 추가해주어야할까요 ??

**Comment by butter-free** [comment]
@dlrjswns 

현재 저희 피그마에 있는 기획내용에서는 지도화면에 검색창에 대한 내용이 없는것으로 보여서
searchBar 처리가 필요한지 확인이 필요할 것 같아요!
