### ISSUE TITLE
Tuist Dependency issue

### ISSUE THREAD

**Issue by dlrjswns** [Connect-SideProject/connect-iOS#5]
저희 MapVC에 bottom popup이 필요한거 같아서 FloatingPanel 라이브러리를 추가하려하는데 SPM이 존재하지않더라구요 !! 기존에 시원님 알려주신 절차대로 진행하려면 Dependencies부분에 추가해줘야하는데 어떻게 해야할까요 ??

**Comment by butter-free** [comment]
@dlrjswns 

해당 라이브러리의 Installation 문서 내용을 보니 SPM 지원을 하는것 같아요
SPM을 지원하지 않는 외부 라이브러리에 대한 처리는 좀더 알아봐야 겠네요

우선은 저희 README.md의 내용과 같이 아래처럼 처리후에 동작확인 부탁드립니다

* Dependencies.swift

```swift
import ProjectDescription

let dependencies = Dependencies(
  swiftPackageManager: [
    .remote(
      url: "https://github.com/ReactorKit/ReactorKit.git", 
      requirement: .upToNextMajor(from: "3.0.0")          
    ),
    .remote(
      url: "https://github.com/SnapKit/SnapKit.git",
      requirement: .upToNextMajor(from: "5.0.1")
    ),
   .remote(
      url: "https://github.com/scenee/FloatingPanel.git", // 추가 하려는 원격 저장소 주소
      requirement: .upToNextMajor(from: "2.5.3")           // 해당 라이브러리의 버전.
    )
  ],
  platforms: [.iOS]
)
```

* Project.swift

```swift
let targets = [
  /// 앱 메인.
  Target(
    name: projectName,
    platform: .iOS,
    product: .app,
    bundleId: "\(bundleID)",
    deploymentTarget: .iOS(targetVersion: "15.0", devices: [.iphone]),
    infoPlist: .extendingDefault(with: infoPlist),
    sources: "Sources/**", 
    resources: "Resources/**",
    dependencies: [
      .external(name: "ReactorKit"),
      .external(name: "SnapKit"),
      .external(name: "FloatingPanel") // 새로 Dependencies.swift에 추가한 라이브러리의 이름
    ],
    settings: settings
  ),
```

**Comment by dlrjswns** [comment]
Generating workspace connect.xcworkspace
Generating project connect
Generating project FloatingPanel
Generating project ReactorKit
Generating project RxSwift
Generating project SnapKit
Generating project WeakMapTable
Trying to add a file at path /Users/igeonjun/connect-iOS/Resources/DaumMap.embeddedframework/DaumMap.framework/DaumMap to a build phase that hasn't been added to the project.
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose

지금 시원님이 말씀하신 부분하고 tuist fetch이후 tuist generate했는데 위와 같은 오류가 뜹니다 !!

**Comment by butter-free** [comment]
@dlrjswns 
로그의 마지막 내용으로는 카카오맵 api 관련 파일을 프로젝트에 추가될때 문제가 되는것 같은데요
Dependencies 추가 이전에 generate 하면 정상적으로 진행이 되는지 확인 부탁드립니다

**Comment by dlrjswns** [comment]
지금 FloatingPanel추가한 부분을 빼고 tuist fetch -> tuist generate 를 하여도 위와 똑같은 오류가 뜨네요, 기존에 저 오류가 없었는데 왜 갑자기 뜨는걸까요 허허...

**Comment by dlrjswns** [comment]
저 살짝 알아봤는데 현재 Daum.embeddedframework이 부분이 Resources폴더에다가 끌어놨는데 이를 tuist에서 적용해주지않아서 생긴 문제로 보이는데 한번 찾아보도록 하겠습니다 !!

**Comment by dlrjswns** [comment]
KakaoMap Tuist로 추가관련 문제 
1. KakaoMap을 사용하기위해서 헤더파일, DaumMap프레임워크, sqlite를 포함한 여러가지 라이브러리를 추가해야함 
2. tuist generate를 하게되면은 위 파일들이 전부 날라감
-> 저희 다음주에 오프라인으로 뵐때 tuist로 저 부분 추가해주는법에 대해 이야기해보면 좋을꺼같아서 남겨둡니다 !!

**Comment by Do-hyun-Kim** [comment]
넵 그전 까지 한번 추가로 알아 보겠습니다. 오늘 한번 Source Tree로 제 Home Branch로 Check out했는데 DaumMap BridgeHeaderfile 뿐만 아니라 소스도 가져오더라고여 ㅠ

<img width="509" alt="스크린샷 2022-06-19 오후 4 05 27" src="https://user-images.githubusercontent.com/23008224/174469818-3a00a75e-9a90-4d01-bc55-b8076122718a.png">
p
